# To install pip, Docker, Docker compose, Docker SDK for Python and all corresponding dependencies
# Also creating the group docker and adding user to the group

- name: VM configuration
  hosts: becode@vmsdt-pisharodi.becode.org
  become: true
  gather_facts: false
  vars_files: pass.yaml

  vars:
    docker_user: becode
    docker_group: docker

  tasks:
    - name: Install python pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes
      when: false
    
    - name: Installing system packages needed for docker 
      ansible.builtin.apt: 
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - ca-certificates 
        - curl 
        - gnupg
        - lsb-release
      when: false

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: false

    - name: Setting up repo for docker
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        
      when: false

    - name: Instaling docker
      apt:
        name: "{{ item }}"
        state: present
        purge: false
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
      when: false
    

   # Manage Docker as a non-root user 

    - name: Adding user and to docker group
      user: 
        name: "{{ docker_user }}"
        groups: "{{ docker_group }}"
        state: present
        append: yes
      #become: yes
      #become_user: "{{ docker_user }}"
      #become_method: sudo
      when: false

    - name: Install Docker SDK for python
      pip:
        name: "{{ item }}"
        state : present
      loop: 
        - docker
        - docker-compose
        - jsondiff
      when: false

 